name: Clang Format and Clang Tidy
on:
  push:
    branches: [develop, stable]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clang Format
        uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "main.c"
          style: "file"
      - name: GCC Check
        run: gcc main.c -fsyntax-only -Wall -Werror -o /dev/null